### Introduction to OOP Python

   One of the popular approach to slove a programming problem by creating an objects, This is known as Object Oriented Programming<br>
   
   An object as two characteristics<br>:
   1.attributes(name,age,color)<br>
   2.behaviour(learn,study,singing,dance)<br>
   
   In Python the concept OOP follow  these things:<br>
   1.Inheritance<br>
   2.Encapsulation<br>
   3.Polymorphism<br>
   
   class:<br>
         A class is a blue of the objects<br>
   object:<br>
         Blue print of class or Instance of the class or Logical entity<br>
         
 

** class classname:<br>
    #some functions and variables<br>
    #function----used to perform the specific activity<br>
    #variables--data(memory)<br>

In [7]:
def test():
    print('Test() for function')
    return
test()
    

Test() for function


In [9]:
class Demo:
    def test(self):
        print("Test() for the class and method")
        return
obj = Demo()
obj.test()

Test() for the class and method


In [14]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact = fact * n
            n = n-1
        return fact
p1 = Demo1()
print(p1.fact(5))

120


In [21]:
class Demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self,p1,p2):
        print("p1 = ",p1)
        print("p2 = ",p2)
c1 = Demo2()
c1.accept(10,20)
c1.display(10,20)

p1 =  10
p2 =  20


In [23]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
        
    def add(self,p1,p2):
        return p1 + p2
c1 = Demo2(10,20)
print(c1.add(100,200))   

300


In [31]:
# Some inheritance
#parent class
class person(object):
      #constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#Derived class
class Employee(person):
    def isEmployee(self):
        return True
    
emp = person("Anil")
print(emp.getName(),emp.isEmployee())

emp1 = Employee("Arvind")
print(emp1.getName(),emp1.isEmployee())


Anil False
Arvind True


In [28]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [34]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [36]:
lst = [1,2.6,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [38]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape) 

(2, 3)
(3, 2)


In [40]:
# Re-shape the given array
# numpy.reshape(arrayname,reshape,order='C')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# Append some data--Horizontally
# Append some data--vertical

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [43]:
# Append some data--vertical
# vstack(array1,array2) --will be arranged in automatically

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [45]:
# Generate random number from NP

a1 = np.random.normal(5,0.5,10)
print(a1)

[5.00711333 4.74301141 4.31074921 5.46201794 5.15711661 5.42621995
 5.04688298 5.08437241 4.72905643 4.47066674]


In [46]:
#numpy.zeros and numpy.one()

#Generate an array with all zeros -- numpy.zeros()

#numpy.zeros(shape,dtype = float,order = 'C')

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [48]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [57]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2] = 5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [59]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2][3] = 14
np.asarray(A)[3][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1 16]]


In [61]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [63]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [64]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First row : ",a1[0])

First row :  [1 2 3]


In [65]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second row : ",a1[0])

Second row :  [1 2 3]


In [67]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Siling column : ",a1[:,1])

Siling column :  [2 5]


In [68]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Siling last column : ",a1[:,2])

Siling last column :  [3 6]


In [70]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1:2])

Row and Column [[4 5 6]]


In [73]:
a1 = np.array([(1,2,3),(4,5,6)])
print("column and row",a1[2:1])

column and row []


In [75]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:1])

Row and Column [4]


In [77]:
a1 = np.random.normal(5,1,10)
print(a1)

[5.5161919  5.46316787 5.09444618 4.3707544  5.42565479 5.5954047
 4.84537285 5.40068041 5.04617487 5.9584247 ]


In [78]:
# Some math Operation on given random numbers
#min     --returns the least number
#max     --returns the large number
#mean    --mean
#median  --median

a1 = np.random.normal(5,0.5,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[4.34317477 5.84532619 5.31820387 5.62218926 4.05593534 5.49881755
 4.81557515 4.46862117 4.65921065 5.37030677]
Min value =  4.055935341552362
Max value =  5.84532619012746
Mean value =  4.999736070649323
Median value =  5.066889507792373


In [81]:
# Multiply of 1D arrays
# numpy,dot(x,y) --

c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

## Pandas Basics

Python is one of the popular programming language for data analysis<br>
Python is offering the Lib called pandas used for importing and analyzing pretty much faster andeasier also<br>
Pandas data frames<br>
       Data analysis with Python<br>
Pandas Data Frames Data Analysis with Python<br>

In [4]:
import pandas as pd
dict = {"Name":["Anil","Arvind","Akil","Ajay"],"EmailID":["anil1gmail.com","arvind2@gmail.com","akil3@gmail.com","ajay4@gmail.com"],
       "MobileNumber":[111,222,333,444],"Address":["Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)

     Name            EmailID  MobileNumber Address
0    Anil     anil1gmail.com           111     Hyd
1  Arvind  arvind2@gmail.com           222     Hyd
2    Akil    akil3@gmail.com           333     Hyd
3    Ajay    ajay4@gmail.com           444     Hyd


In [5]:
b.index = ["01","02","03","04"]
print(b)

      Name            EmailID  MobileNumber Address
01    Anil     anil1gmail.com           111     Hyd
02  Arvind  arvind2@gmail.com           222     Hyd
03    Akil    akil3@gmail.com           333     Hyd
04    Ajay    ajay4@gmail.com           444     Hyd


In [7]:
import pandas as pd
dict = {"Name":["Anil","Arvind","Akil","Ajay"],"EmailID":["anil1gmail.com","arvind2@gmail.com","akil3@gmail.com","ajay4@gmail.com"],
       "MobileNumber":[111,222,333,444],"Address":["Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
b.index = ["01","02","03","04"]
print(b)

      Name            EmailID  MobileNumber Address
01    Anil     anil1gmail.com           111     Hyd
02  Arvind  arvind2@gmail.com           222     Hyd
03    Akil    akil3@gmail.com           333     Hyd
04    Ajay    ajay4@gmail.com           444     Hyd


In [20]:
def check(s1, s2): 
    if(sorted(s1) == sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.") 
s1 = "abc"
s2 = "ert"
check(s1,s2)

The strings aren't anagrams.


In [29]:
def check(s1,s2):
    if len(s1)!=len(s2):
        print(False)
    elif:
        
    else:
        print(True)
s1="abc"
s2="bsd"
check(s1,s2)

SyntaxError: invalid syntax (<ipython-input-29-2d96bd674769>, line 4)